server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa_sql?serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.104.66.106:3306/oa_sql?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#redis
redis:
  port: 6379
  host: 127.0.0.1
  database: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000
